import os
import pytest
from pathlib import Path
from unittest.mock import Mock, patch

from skelantic.commons.codegen import to_pascal, to_snake, map_type, CodeGenerator

def test_map_type():
    assert map_type("int") == "int"
    assert map_type("decimal") == "float"
    assert map_type("bool") == "bool"
    assert map_type("any") == "Any"
    assert map_type("enum[foo]") == "str"
    assert map_type("other") == "str"

def test_to_pascal():
    assert to_pascal("README.md") == "ReadmeMd"
    assert to_pascal(".github") == "DotGithub"
    assert to_pascal("01-strategy") == "Node01Strategy"
    assert to_pascal("nda-*.md") == "NdaAnyMd"
    assert to_pascal("**/*.md") == "GlobAnyMd"
    assert to_pascal("**/*") == "GlobAny"
    assert to_pascal("{slug:words(1,5)}") == "Slug"
    assert to_pascal("{year}-{month}-{day}.md") == "YearMonthDayMd"
    assert to_pascal("test_file_name.txt") == "TestFileNameTxt"

def test_to_snake():
    assert to_snake("ReadmeMd") == "readme_md"
    assert to_snake("DotGithub") == "dot_github"
    assert to_snake("SalesCockpitTemplate") == "sales_cockpit_template"

def test_codegen_init():
    cg = CodeGenerator(".")
    assert cg.base_dir == "."
    assert cg.template_models == {}

def test_codegen_generate_repo_graph():
    cg = CodeGenerator(".")
    config = {
        "directories": {
            "sales": {
                "description": "Sales Docs",
                "files": {
                    "README.md": {
                        "description": "Readme",
                        "model": "SalesReadme",
                        "property": "main_readme"
                    }
                }
            },
            "01-strategy": {
                "description": "Strategy",
                "directories": {
                    "{slug}": {
                        "description": "A strategy"
                    }
                }
            }
        }
    }
    
    code = cg.generate_repo_graph(config)
    assert "class RepoGraph(DirectoryNode):" in code
    assert "class Sales(DirectoryNode):" in code
    assert "class SalesReadme(MarkdownNode):" in code
    assert "def main_readme(self) -> Optional[RepoGraph.Sales.SalesReadme]:" in code
    assert "class Node01Strategy(DirectoryNode):" in code
    assert "class Slug(DirectoryNode):" in code
    assert "def slug_list(self) -> List[RepoGraph.Node01Strategy.Slug]:" in code
    assert "path_params: PathParams" in code
    assert "class PathParams(BaseModel):" in code
    assert "slug: str" in code

@patch('skelantic.commons.config.ConfigLoader.load_config')
def test_codegen_generate(mock_load_config):
    mock_load_config.return_value = {
        "files": {
            "README.md": {}
        }
    }
    
    cg = CodeGenerator(".")
    code = cg.generate("dummy_path")
    assert "THIS FILE IS AUTO-GENERATED BY SKELANTIC" in code
    assert "class RepoGraph(DirectoryNode):" in code
    assert "__SKELANTIC_NODE_MAP__ =" in code
    assert "'README.md': RepoGraph.ReadmeMd" in code

def test_codegen_parse_template_nodes():
    from skelantic.templates.parser import LineNode, Variable, TemplateNode
    
    # Create mock nodes
    var1 = Variable("title", "str")
    line1 = LineNode(variables=[var1])
    var2 = Variable("count", "int")
    line2 = LineNode(variables=[var2])
    
    block_node = TemplateNode("block", "MyBlock", [line2])
    
    nodes = [line1, block_node]
    
    cg = CodeGenerator(".")
    classes_out = {}
    cg._parse_template_nodes(nodes, "MyTemplate", classes_out)
    
    assert "MyTemplate" in classes_out
    assert classes_out["MyTemplate"]["title"] == "str"
    assert classes_out["MyTemplate"]["MyBlock"] == "'MyTemplateMyblockBlock'"
    
    assert "MyTemplateMyblockBlock" in classes_out
    assert classes_out["MyTemplateMyblockBlock"]["count"] == "int"

@patch('glob.glob')
@patch('builtins.open')
def test_codegen_generate_templates_graph(mock_open, mock_glob):
    mock_glob.return_value = ["C:/repo/.skelantic/templates/test.md"]
    # Mock file read
    mock_open.return_value.__enter__.return_value.read.return_value = "{{title:str}}"
    
    cg = CodeGenerator("C:/repo")
    code = cg.generate_templates_graph()
    
    assert "class Templates:" in code
    assert "class DotSkelantic:" in code
    assert "class Templates:" in code
    assert "class Test(BaseModel):" in code
    assert "title: Optional[str] = None" in code
    assert "rel_path: Optional[str] = None" in code

